name: Mi primer pipeline

on: [push, pull_request]
jobs: 
  master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configura .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      
      - name: Probar aplicacion
        run: |
          dotnet test

      - name: Compilar aplicacion
        run: |
          dotnet build